/*
 * VANILLA Modules
 * Copyright (C) 2026 Samed
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 2 only,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * See the LICENSE file for the full license text.
 */

#ifndef VANILLA_WINDOW_INPUT_H
#define VANILLA_WINDOW_INPUT_H

#include "primitives.h"
#include "configuration.h"
#include "main.h"

typedef struct { ID32 slot; ID16 generation; } EventBindID;

typedef enum {
    VANILLA_INPUTEVENT_KEY_A,
    VANILLA_INPUTEVENT_KEY_B,
    VANILLA_INPUTEVENT_KEY_C,
    VANILLA_INPUTEVENT_KEY_D,
    VANILLA_INPUTEVENT_KEY_E,
    VANILLA_INPUTEVENT_KEY_F,
    VANILLA_INPUTEVENT_KEY_G,
    VANILLA_INPUTEVENT_KEY_H,
    VANILLA_INPUTEVENT_KEY_I,
    VANILLA_INPUTEVENT_KEY_J,
    VANILLA_INPUTEVENT_KEY_K,
    VANILLA_INPUTEVENT_KEY_L,
    VANILLA_INPUTEVENT_KEY_M,
    VANILLA_INPUTEVENT_KEY_N,
    VANILLA_INPUTEVENT_KEY_O,
    VANILLA_INPUTEVENT_KEY_P,
    VANILLA_INPUTEVENT_KEY_Q,
    VANILLA_INPUTEVENT_KEY_R,
    VANILLA_INPUTEVENT_KEY_S,
    VANILLA_INPUTEVENT_KEY_T,
    VANILLA_INPUTEVENT_KEY_U,
    VANILLA_INPUTEVENT_KEY_V,
    VANILLA_INPUTEVENT_KEY_W,
    VANILLA_INPUTEVENT_KEY_X,
    VANILLA_INPUTEVENT_KEY_Y,
    VANILLA_INPUTEVENT_KEY_Z,

    VANILLA_INPUTEVENT_KEY_0,
    VANILLA_INPUTEVENT_KEY_1,
    VANILLA_INPUTEVENT_KEY_2,
    VANILLA_INPUTEVENT_KEY_3,
    VANILLA_INPUTEVENT_KEY_4,
    VANILLA_INPUTEVENT_KEY_5,
    VANILLA_INPUTEVENT_KEY_6,
    VANILLA_INPUTEVENT_KEY_7,
    VANILLA_INPUTEVENT_KEY_8,
    VANILLA_INPUTEVENT_KEY_9,

    VANILLA_INPUTEVENT_KEY_SPACE,
    VANILLA_INPUTEVENT_KEY_ENTER,
    VANILLA_INPUTEVENT_KEY_ESCAPE,
    VANILLA_INPUTEVENT_KEY_TAB,
    VANILLA_INPUTEVENT_KEY_BACKSPACE,

    VANILLA_INPUTEVENT_KEY_LEFT,
    VANILLA_INPUTEVENT_KEY_RIGHT,
    VANILLA_INPUTEVENT_KEY_UP,
    VANILLA_INPUTEVENT_KEY_DOWN,

    VANILLA_INPUTEVENT_KEY_LEFT_SHIFT,
    VANILLA_INPUTEVENT_KEY_RIGHT_SHIFT,
    VANILLA_INPUTEVENT_KEY_LEFT_CONTROL,
    VANILLA_INPUTEVENT_KEY_RIGHT_CONTROL,
    VANILLA_INPUTEVENT_KEY_LEFT_ALT,
    VANILLA_INPUTEVENT_KEY_RIGHT_ALT,
    VANILLA_INPUTEVENT_KEY_LEFT_SUPER,
    VANILLA_INPUTEVENT_KEY_RIGHT_SUPER,

    VANILLA_INPUTEVENT_KEY_F1,
    VANILLA_INPUTEVENT_KEY_F2,
    VANILLA_INPUTEVENT_KEY_F3,
    VANILLA_INPUTEVENT_KEY_F4,
    VANILLA_INPUTEVENT_KEY_F5,
    VANILLA_INPUTEVENT_KEY_F6,
    VANILLA_INPUTEVENT_KEY_F7,
    VANILLA_INPUTEVENT_KEY_F8,
    VANILLA_INPUTEVENT_KEY_F9,
    VANILLA_INPUTEVENT_KEY_F10,
    VANILLA_INPUTEVENT_KEY_F11,
    VANILLA_INPUTEVENT_KEY_F12,

    VANILLA_INPUTEVENT_KEY_INSERT,
    VANILLA_INPUTEVENT_KEY_DELETE,
    VANILLA_INPUTEVENT_KEY_HOME,
    VANILLA_INPUTEVENT_KEY_END,
    VANILLA_INPUTEVENT_KEY_PAGE_UP,
    VANILLA_INPUTEVENT_KEY_PAGE_DOWN,

    VANILLA_INPUTEVENT_KEY_CAPS_LOCK,
    VANILLA_INPUTEVENT_KEY_NUM_LOCK,
    VANILLA_INPUTEVENT_KEY_SCROLL_LOCK,

    VANILLA_INPUTEVENT_KEY_PRINT_SCREEN,
    VANILLA_INPUTEVENT_KEY_PAUSE,

    VANILLA_INPUTEVENT_KEY_KP_0,
    VANILLA_INPUTEVENT_KEY_KP_1,
    VANILLA_INPUTEVENT_KEY_KP_2,
    VANILLA_INPUTEVENT_KEY_KP_3,
    VANILLA_INPUTEVENT_KEY_KP_4,
    VANILLA_INPUTEVENT_KEY_KP_5,
    VANILLA_INPUTEVENT_KEY_KP_6,
    VANILLA_INPUTEVENT_KEY_KP_7,
    VANILLA_INPUTEVENT_KEY_KP_8,
    VANILLA_INPUTEVENT_KEY_KP_9,

    VANILLA_INPUTEVENT_KEY_KP_DECIMAL,
    VANILLA_INPUTEVENT_KEY_KP_DIVIDE,
    VANILLA_INPUTEVENT_KEY_KP_MULTIPLY,
    VANILLA_INPUTEVENT_KEY_KP_SUBTRACT,
    VANILLA_INPUTEVENT_KEY_KP_ADD,
    VANILLA_INPUTEVENT_KEY_KP_ENTER,
    VANILLA_INPUTEVENT_KEY_KP_EQUAL,

    VANILLA_INPUTEVENT_MOUSE_LEFT,
    VANILLA_INPUTEVENT_MOUSE_RIGHT,
    VANILLA_INPUTEVENT_MOUSE_MIDDLE,

    VANILLA_INPUTEVENT_MOUSE_BUTTON_4,
    VANILLA_INPUTEVENT_MOUSE_BUTTON_5,
    VANILLA_INPUTEVENT_MOUSE_BUTTON_6,
    VANILLA_INPUTEVENT_MOUSE_BUTTON_7,
    VANILLA_INPUTEVENT_MOUSE_BUTTON_8,

    VANILLA_INPUTEVENT_MOUSE_MOVE,
    VANILLA_INPUTEVENT_MOUSE_SCROLL,

    VANILLA_INPUTEVENT_WINDOW_CLOSE,
    VANILLA_INPUTEVENT_WINDOW_FOCUS_GAINED,
    VANILLA_INPUTEVENT_WINDOW_FOCUS_LOST,

    VANILLA_INPUTEVENT_WINDOW_MINIMIZED,
    VANILLA_INPUTEVENT_WINDOW_MAXIMIZED,
    VANILLA_INPUTEVENT_WINDOW_RESTORED,

    VANILLA_INPUTEVENT_WINDOW_RESIZED,

    VANILLA_INPUTEVENT_LIMIT
} VANILLA_InputEvent;

typedef enum {
    VANILLA_INPUTSTATE_NONE     = 0,
    VANILLA_INPUTSTATE_ACTIVE   = 1 << 0,
    VANILLA_INPUTSTATE_PRESSED  = 1 << 1,
    VANILLA_INPUTSTATE_RELEASED = 1 << 2
} VANILLA_InputState;

typedef struct {
    void (**functions)(VANILLA_InputState);
    uint32_t functionCount;
    uint16_t* generations;
} VANILLA_InputEventBinding;

typedef struct {
    VANILLA_InputEvent* events;
    VANILLA_InputState* states;

    bool* isHeld;
    bool* eventFlags;

    VANILLA_InputEventBinding* bindings;

    uint32_t count;
} VANILLA_InputEventList;

#endif // VANILLA_WINDOW_INPUT_H